### PR TITLE
Accept alpha/num/space/parentheses

### PR DESCRIPTION
**Pull request by skng5**
Issue #310

### CODE REVIEW

**Comment by skng5** [comment]
What other characters will we need to accept?

**Comment by skng5** [comment]
Found cases of trailing spaces it's not catching.

**Comment by dkinzer** [comment]
@skng5 I'm not a regex guru, can you please give me some examples of what the expected behavioris you are looking for:

For example  from IRB expected:
```
"????!!!David &&&!!! World".gsub(/[^[:alnum:])]*$/, "")
```

**Comment by dkinzer** [comment]
Above results in the following output:

```
"????!!!David &&&!!! World"

```

**Comment by dkinzer** [comment]
OK, I get it.  Anything that is not either an alpha numeral or ), and is at the end of a string gets deleted.  In that case, looks good.

**Pull request merged**
