### PR TITLE
BL-1782 Add New GTM Code Snippets

### PR DESCRIPTION
**Pull request by cdoyle-temple**
Also removes @nonce, since no content security policy is place it is not needed.

If CSP is needed in future, rails has a built-in initializer to handle, including nonce values: config/initializers/content_security_policy.rb

Possible alternatives to UA gem: 
https://github.com/koic/gtm_rails 
https://github.com/rcs/google-tag-manager-rails

### CODE REVIEW

**Comment by ebtoner** [comment]
@cdoyle-temple -- looks like this is currently failing in circleci due to the bundler change.

**Comment by ebtoner** [comment]
@dkinzer -- can you help me with this? This ticket adds the integration with the new Google Tag Manager setup. Chris opened this last Friday before he left for vacation and it needs to be merged and released before the end of the month, when the GA4 deadline is. 

However, the CircleCi tests are failing currently, due to an issue with the bundler, I think. Can you see if you can fix that?

**Review by dkinzer — APPROVED** [review]

**Comment by dkinzer** [comment]
@ebtoner I'm taking a look now.

**Comment by ebtoner** [comment]
Thanks David! It's passing now, so I'm going to merge and test on QA.

**Pull request merged**
