### PR TITLE
Adds rubocop config used in rails project.

### PR DESCRIPTION
**Pull request by dkinzer**
REF: BL-140

This change adds the same rubocop config applied to the rails project with some minor modifications specific to this project.

Then, I automatically applied the fixes to our code.

### CODE REVIEW

**Comment by bibliotechy** [comment]
What do you mean automatically applies fixes?

**Comment by dkinzer** [comment]
I ran `rubocop $PATH -a`  to auto correct the errors it found. 

(I did started by making these steps manually, but it turns out there where so many issues that it would have taken me too long to do manually... There were over 1000 suggested corrections.).

**Comment by bibliotechy** [comment]
@dkinzer I'm going to hold off on this one till we finish this sprint, to avoid creating a bunch of merge conflicts for people with open branches.

**Comment by dkinzer** [comment]
Makes sense.

**Comment by bibliotechy** [comment]
Alright, happy to merge this once you remove your vim and tags stuff from `.gitignore`.

**Comment by dkinzer** [comment]
oops, forgot about that.

**Comment by dkinzer** [comment]
done.

**Pull request merged**
