### PR TITLE
BL-72 create rake task to harvest incremental oai updates

### PR DESCRIPTION
**Pull request by skng5**
Addresses Issue #BL-72

### CODE REVIEW

**Comment by bibliotechy** [comment]
This only harvests the first page of results, right? I don't see any handling of resumption tokens in here. Is it worth dropping in the [ruby-oai client](https://github.com/code4lib/ruby-oai) to deal with that?

**Comment by skng5** [comment]
@bibliotechy Yes, only the first page. The ruby-oai client is well worth pursuing.

**Comment by skng5** [comment]
@bibliotechy - I've added in the resumption token without the OAI gem. It's harvesting based on the resumption token. There are thousands of records, and I'm waiting to get to the end of the list of files so I can verify the loop exit condition.

**Comment by bibliotechy** [comment]
Superseded by #83

**Pull request closed without merging**
