### PR TITLE
Bl 1671 update search results primary metadata display

### PR DESCRIPTION
**Pull request by cdoyle-temple**

### CODE REVIEW

**Review by ebtoner — CHANGES_REQUESTED** [review]
@cdoyle-temple -- There are a couple of things that you've included from the mockup referenced in BL-1671 that should not be included in this ticket. They have primarily to do with the availability displays which we worked on in the spring, during which we made some decisions not reflected in that mockup. Apologies for the confusion!

Please remove the following: 
- "Check Availablity" button text: revert back to "Available" 
- "Format" text: revert back to "Type" 
- "Online" card heading: restore headings in app/views/catalog/_hathitrust_button.html.erb and app/views/catalog/_online_availability_button.html.erb

**Comment by ebtoner** [comment]
@cdoyle-temple -- "Check Availability" change still needs to be reverted. Thanks!

**Comment by cdoyle-temple** [comment]
@ebtoner That's weird, I know I changed it. But here it is, again.

**Comment by ebtoner** [comment]
Available misspelled

**Review by ebtoner — APPROVED** [review]

**Pull request merged**
