### PR TITLE
Add javascript testing.

### PR DESCRIPTION
**Pull request by dkinzer**
Adds the Jest JavaScript testing framework to our project with some initial tests and a documentation.

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer I'm just wondering what made you choose Jest over some of the other options out there since we aren't using react.

**Comment by dkinzer** [comment]
@sensei100 I chose it because the framework is not actually react specific and all the blog post I read pretty much said that this one is the current champion.

**Comment by dkinzer** [comment]
imho, they are all a pain to work with.

**Comment by sensei100** [comment]
@dkinzer I was just curious.  I haven't written javascript tests before, but have used Jasmine and Mocha.  This site talked about AVA and Tape, which I haven't heard of before.  I just wondered what your process was for deciding on one. https://raygun.com/blog/javascript-unit-testing-frameworks/

**Comment by dkinzer** [comment]
Yeah, my plan was to try a bunch and see which one I liked.  But then I spent all of Friday getting Jest to work with our setup.  👿 

If you have some good experience with those other frameworks we could give them a try too.  I have bad experiences with casperjs/phantomjs and selenium based tests (So I wouldn't recommend them).

**Comment by bibliotechy** [comment]
This sees like a good idea, though I have nothing to add in terms of what test framework to use. @sensei100 , since you've been doing most of the JS lately, I'll leave this up to your discretion.

**Comment by sensei100** [comment]
@dkinzer @bibliotechy My only hesitation in using this is that because it is relatively new, there isn't as much documentation and resources when we get stuck. That was a challenge with stimulus as times.  Jasmine has been around a long time and has more to rely on, but I have never actually written tests in it.

**Comment by dkinzer** [comment]
@sensei100, if it helps, in terms of syntax jest and jasmine are exactly the same.  In fact jest used to use jasmine underneath. (I'm not 100% sure it does anymore but I know the syntax is still the same).

Also, Jest has been around since 2014.  So it's not entirely new.  And and added benefit is that if we ever want to incorporate some React components then Jest is better equipped to test those.

**Comment by dkinzer** [comment]
I do agree that Stimulus has an issue with bad documentation.  In fact the hardest part of this PR was figuring out how to write a test for Stimulus.  Though I think I would have had some similar issues had I used another testing framework.

Stimulus uses qunit as their testing framework.  I didn't go with that because it seemed harder to set up.

**Pull request merged**
