### PR TITLE
BL-1781: cob_index version to latest (5cd134b0500f5)

### PR DESCRIPTION
**Pull request by dkinzer**

### CODE REVIEW

**Comment by dkinzer** [comment]
OK I'm closing this and redoing with no swagger changes.

**Comment by dkinzer** [comment]
wrong pr

**Comment by ebtoner** [comment]
@dkinzer -- please add ITM fields in addition to HLD, just to be on the safe side.

**Comment by ebtoner** [comment]
@dkinzer -- this looks like fine. I updated it to "Ready For Review" so that I can approve. Let me know if you want me to merge.

**Review by ebtoner — APPROVED** [review]

**Pull request merged**
