### PR TITLE
Use cob_index locations map to avoid duplication.

### PR DESCRIPTION
**Pull request by dkinzer**

### CODE REVIEW

**Comment by bibliotechy** [comment]
👍

**Review by sensei100 — COMMENTED** [review]
@dkinzer What do we want to do about the locations.rake task then? It doesn't make sense to kept here if we aren't using that file anymore.

**Comment by dkinzer** [comment]
Good point @sensei100. Let's move that to cob_index.

**Comment by dkinzer** [comment]
Although, hmmm.. it's tricker because right now cob_index is blissfully unaware of any alma configs I think.

**Comment by bibliotechy** [comment]
@dkinzer cob_index knows about Alma configs...though maybe not in the most re-usable way https://github.com/tulibraries/cob_index/blob/main/lib/cob_index.rb#L40-L44

**Comment by dkinzer** [comment]
Oh, in that case, 😎

**Comment by bibliotechy** [comment]
@dkinzer I'd say that once https://github.com/tulibraries/cob_index/pull/143 is merged, update this to remove that rake task and we're good to go!

**Comment by dkinzer** [comment]
@bibliotechy, done.  But I can't merge because it's still blocked until it gets at least one official approval.

**Review by bibliotechy — APPROVED** [review]

**Pull request merged**
