### PR TITLE
Fix first boolean operator dropped.

### PR DESCRIPTION
**Pull request by dkinzer**
REF BL-253

The `parse_queries` method used by some of our search_builder processing
is erroneoulsy dropping boolean operators from the first query.

This change refactors that method so that no information is lost.

 ## QA Steps
 * In libqa or locally run an advanced search query where the first query is "contains" "NOT moon" and the second query is connected with (*) AND  "contains" full.  Note the results.
 * Pull in the code and run the same query
 - [ ] Verify that the new search is limited as expected.

### CODE REVIEW

**Comment by bibliotechy** [comment]
I was not able to replicate the expected behavior. Using the test fixture data only, I performed a search for:
all fields | contains | NOT Whiteman
and
all fields | contains | Philadelphia

I expected " A Philadelphia perspective : the diary of Sidney George Fisher covering the years, 1834-1871 / edited by Nicholas B. Wainwright." to not be present, but it was present.

However, if I perform

all fields | contains | Philadelphia
not
all fields | contains | Whiteman

I get the expected result of " A Philadelphia perspective : the diary of Sidney George Fisher covering the years, 1834-1871 / edited by Nicholas B. Wainwright." not being present.

**Comment by dkinzer** [comment]
ok, i'll take a look at it once i'm done with BL-247

**Comment by dkinzer** [comment]
> I was not able to replicate the expected behavior. Using the test fixture data only, I performed a search for:
all fields | contains | NOT Whiteman

@bibliotechy I think that because you are searching "all fields" it's returning records when any field satisfies the "NOT Whiteman" criteria.  Thus, this might explain your observation.

**Comment by bibliotechy** [comment]
OK, limited to a single field and same result:

title | contains| Handbook
and
title | contains | NOT Genetic

But "Handbook of genetic skin disorders"  is listed.

However, with:

title | contains | Handbook
NOT
title | contains | Genetic

"Handbook of genetic skin disorders"  does not show up in the results list.

**Comment by dkinzer** [comment]
> title | contains| Handbook
> and
> title | contains | NOT Genetic

Can you please test with 
title | contains| NOT Genetic
and
title | contains |  handbook

The issue is with how search is handled by the first item not the rest.  I don't know if advanced query updates the other queries the way it does the first one.

**Comment by bibliotechy** [comment]
Same result

**Comment by dkinzer** [comment]
ok, thanks.  I think I see the issue.  I't looking for "NOT,  'NOT Handbook'" . :) I'll need to also update the passed in value.

**Comment by dkinzer** [comment]
ok, I just pushed a commit that removes the prefix boolean from the search term.

**Pull request merged**
