### PR TITLE
BL-1133: Fix drop-down selection accessibility issue.

### PR DESCRIPTION
**Pull request by dkinzer**
The bootstrap-select library is interfering with the accessibility use
case of drop-down select menus.  Removing it from our app fixes the
issue.

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer That library is what we use to auto-fill facets in the advanced search forms.  I don't think they would want to lose that.

**Comment by dkinzer** [comment]
OK, maybe playing around with the order could also do the trick or updating the library if possible. And if not maybe limiting it just advanced pages.  I'll look into it on Monday.

**Comment by dkinzer** [comment]
@sensei100 OK, locally I got it working by updating the version of bootstrap select.  Also I removed the bootstrap-rails-gem because it seems to just need the yarn setup to work (locally).

**Review by sensei100 — APPROVED** [review]

**Comment by sensei100** [comment]
@dkinzer I'm so glad you figured this one out!

**Pull request merged**
