### PR TITLE
Refactor specs

### PR DESCRIPTION
**Pull request by sensei100**
Lots of changes in the spec files here.
- Add the rubocop gem and changed spec files to get rid of syntax offenses
- Uncomment methods in the spec_helper file
- Cleans up code by removing explicit statements of spec type,  be_methodname rather that expressing a boolean value, using capybara negative selectors 
-Add context to conditional specs

### CODE REVIEW

**Comment by sensei100** [comment]
I'm not sure that I'm the one to make a decision about adding rubocop to travis.  @bibliotechy  What do you think?

**Comment by bibliotechy** [comment]
👍

**Comment by sensei100** [comment]
Okay, I haven't worked with Travis configurations, so I will need to look into how to do that.  Right now, when I run rubocop there are 75 offenses in our code.  Does that mean that all those need to be corrected before Travis will pass?

**Comment by bibliotechy** [comment]
I'd say let's add the config to make this run on travis, merge this and then afterwards we can apply the changes I just made in  https://github.com/tulibraries/tul_cob/pull/190 which should take care of our now failing builds.

**Comment by dkinzer** [comment]
@sensei100 here is a an example of of how to do this on travis.  It's a one liner under the script: tag https://github.com/tulibraries/roper/blob/master/.travis.yml#L8

**Comment by sensei100** [comment]
Since there is another PR for adding Rubocop,  I think this one is ready to merge.

**Pull request merged**
