### PR TITLE
BL-1543: Aug 2021 Release Final updates.

### PR DESCRIPTION
**Pull request by dkinzer**
* Remove donor_info_display field
* Remove feature flag from query links

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer I'm pretty sure specs need to be updated because we removed the query list feature flag.

**Comment by dkinzer** [comment]
Yup.  Thanks.

**Review by sensei100 — COMMENTED** [review]
The feature spec/query_list specs have this:       
visit "catalog/#{item['doc_id']}?query_list=true"
Should we remove those too?

**Comment by dkinzer** [comment]
@sensei100 I think it's ok to leave those

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
