### PR TITLE
Makes the bento search the root of the site.

### PR DESCRIPTION
**Pull request by dkinzer**
REF BL-680

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer I think this will affect links that include the root path.  I know that subject links refer to that. I think that others might as well.  Do we need to change all of those?

**Comment by dkinzer** [comment]
@sensei100 roo_path will be "/" this only afffects the controller and action that queries to root get sent to.  I expected some tests to fail that depend on going to "/" and doing a catalog search.  I'm happy to see only feature tests are failing this way.  Will fix.

**Comment by sensei100** [comment]
@dkinzer This does break some current links.  When I click on a subject link in the record page, it now takes me to an empty bento search.

**Comment by dkinzer** [comment]
@sensei100 good catch, let's fix those links

**Comment by dkinzer** [comment]
@sensei100 ok, I updated the helper method so that it doesn't assume that root_path is where catalog_search should be happening.

**Pull request merged**
