### PR TITLE
[BL-689] Add breadcrumbs to advanced pages.

### PR DESCRIPTION
**Pull request by dkinzer**
REF BL-689

Use breadcrumbs_on_rails gem to add breadcrumbs to the advanced pages
plus books and journals.

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer Will this save the search terms and send them back to their original search state?

**Comment by dkinzer** [comment]
not yet, is that a requirement?

**Comment by sensei100** [comment]
@dkinzer Yes, both Jira tickets asked for the breadcrumb to retain their current search.  Using the link_back_to_catalog blacklight link worked for all controllers to save state.

**Comment by dkinzer** [comment]
Cool, breadcrumbs don't usually save state like that but we can pass any method we like so that can happen.  I'm going to put this aside for now and get back to it later so I can fix the issue with missing bib items that needs to go out on the next prod deploy.

**Pull request merged**
