### PR TITLE
Add a back_to_search button on bookmarks page

### PR DESCRIPTION
**Pull request by sensei100**
BL-581 Links back to search from bookmarks page

### CODE REVIEW

**Comment by ebtoner** [comment]
@dkinzer What happens when a user goes directly to https://library.temple.edu/library-search-faq/beta-feedback? Would the "Back to Search" button be omitted like it is for that button on the full record page? If so, I'm inclined to leave it as "Back to Search" for now.

**Comment by dkinzer** [comment]
@ebtoner sorry, I'm not following, this "Back to Search" button is specific to the bookmarks page.

**Comment by ebtoner** [comment]
We're replicating this button from the one used on the full record pages, though. I'm wondering if the one in Bookmarks will (or could) have the same conditional display.

**Comment by sensei100** [comment]
@ebtoner @dkinzer I was unable to use the same method that the link on the full record pages uses.  It changed the text of the button to Back to Bookmarks and would keep you on the bookmark page when you click it.  So I can't guarantee that it would have the exact same behavior.  I'm not sure how someone would go directly to the bookmarks from the page that you provided though.

**Comment by ebtoner** [comment]
Ooops --- now I see why you both are confused! I provided the wrong link (clearly I'm ready for the weekend). I meant to use https://librarysearch.temple.edu/bookmarks, i.e. when someone might directly access the URL (perhaps if they had saved it in their browser).

**Comment by ebtoner** [comment]
In short, though, let's go ahead and use "Back" then, if that conditional display doesn't work.

**Comment by sensei100** [comment]
This is what they would see: 
screen shot 2018-08-17 at 10 37 13 am

**Comment by sensei100** [comment]
Sorry, that screen shot was taken on the wrong branch.  You would still see the link if you went directly there.

**Comment by dkinzer** [comment]
I think as long as there are bookmarks you will see the link.  But in my opinion that should be OK.

**Comment by ebtoner** [comment]
Agreed.

**Pull request merged**
