### PR TITLE
Initial solr replication request handler

### PR DESCRIPTION
**Pull request by relaxing**
Before merging we need to have our deploy scripts put the correct solrconf fragment in place.

### CODE REVIEW

**Comment by bibliotechy** [comment]
So...what would you see the deployment story being on this? Copy the config over to both solr's, if it is a follower, delete the leader XML?

**Comment by relaxing** [comment]
> So...what would you see the deployment story being on this? Copy the config over to both solr's, if it is a follower, delete the leader XML?

Yeah, that seems like the easiest way to do it from Ansible.

**Comment by relaxing** [comment]
Also put the right IP address and core name into the follower config.

**Comment by dkinzer** [comment]
BL-450 is marked done on Jira so closing this.

**Pull request closed without merging**
