### PR TITLE
BL-162 Links from 856 field and alma api are merged into one list

### PR DESCRIPTION
**Pull request by sensei100**
BL-162 Links coming from the alma api and links coming from Marc 856 fields are merged into one field.

### CODE REVIEW

**Comment by bibliotechy** [comment]
@jennifer
I downloaded a random sample of records and I got an error when trying to do do a search
screenshot-2017-11-1 action controller exception caught
The document object did not have an `availability_facet` key.

**Comment by sensei100** [comment]
@bibliotechy  How do we want to handle records that might not have the availability_facet key?

**Comment by bibliotechy** [comment]
I'm confused why there would be records without some value. Seems like every record should either be Online or At the Library.

**Comment by bibliotechy** [comment]
I'm seeing multiple Online buttons for records with more than one external link. Pretty sure there should only be one. 
screenshot-2017-11-1 availability online - blacklight search results

**Comment by sensei100** [comment]
I don't see any multiple buttons on mine, so I'm not sure what is causing that.

**Pull request merged**
